Fix smells found in workflows

diff --git a/.github/workflows/acceptance.yml b/.github/workflows/acceptance.yml
--- a/.github/workflows/acceptance.yml
+++ b/.github/workflows/acceptance.yml
@@ -29,11 +29,14 @@ jobs:
     outputs:
       acceptance: ${{ steps.changes.outputs.acceptance }}
       backend_all: ${{ steps.changes.outputs.backend_all }}
+    permissions:
+      contents: read
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
 
       - name: Check for backend file changes
-        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
+        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd  # v3.0.0
         id: changes
         with:
           token: ${{ github.token }}
@@ -45,6 +48,8 @@ jobs:
     name: acceptance
     runs-on: ubuntu-22.04
     timeout-minutes: 30
+    permissions:
+      actions: write
     strategy:
       # This helps not having to run multiple jobs because one fails, thus, reducing resource usage
       # and reducing the risk that one of many runs would turn red again (read: intermittent tests)
@@ -57,27 +62,28 @@ jobs:
       # XXX: MATRIX_INSTANCE_TOTAL must be hardcoded to the length of strategy.matrix.instance.
       MATRIX_INSTANCE_TOTAL: 5
       TEST_GROUP_STRATEGY: roundrobin
+      WEBPACK_CACHE_PATH: .webpack_cache
 
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
         name: Checkout sentry
 
-      - uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581 # v2.0.0
+      - name: Setup volta
+        uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581  # v2.0.0
 
       - name: Step configurations
         id: config
         run: |
           echo "webpack-path=.webpack_cache" >> "$GITHUB_OUTPUT"
-          echo "WEBPACK_CACHE_PATH=.webpack_cache" >> "$GITHUB_ENV"
 
       - name: webpack cache
-        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
+        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2  # v4.0.0
         with:
           path: ${{ steps.config.outputs.webpack-path }}
           key: ${{ runner.os }}-v2-webpack-cache-${{ hashFiles('webpack.config.ts') }}
 
       - name: node_modules cache
-        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
+        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2  # v4.0.0
         id: nodemodulescache
         with:
           path: node_modules
@@ -131,4 +137,7 @@ jobs:
       - name: Check for failures
         if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
         run: |
-          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
+          echo "One of the dependent jobs have failed. You may need to re-run it."
+      - name: Fail the pipeline
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: exit 1
diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -28,11 +28,14 @@ jobs:
       backend_dependencies: ${{ steps.changes.outputs.backend_dependencies }}
       backend_any_type: ${{ steps.changes.outputs.backend_any_type }}
       migration_lockfile: ${{ steps.changes.outputs.migration_lockfile }}
+    permissions:
+      contents: read
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
 
       - name: Check for backend file changes
-        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
+        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd  # v3.0.0
         id: changes
         with:
           token: ${{ github.token }}
@@ -43,10 +46,14 @@ jobs:
     needs: files-changed
     name: api docs test
     runs-on: ubuntu-22.04
+    permissions: {}
+    timeout-minutes: 8
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
 
-      - uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581 # v2.0.0
+      - name: Checkout repository
+        uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581  # v2.0.0
 
       - name: Setup sentry python env
         uses: ./.github/actions/setup-sentry
@@ -54,12 +61,14 @@ jobs:
         with:
           snuba: true
 
-      - name: Run API docs tests
+      - name: Add ts-node
         # install ts-node for ts build scripts to execute properly without potentially installing
         # conflicting deps when running scripts locally
         # see: https://github.com/getsentry/sentry/pull/32328/files
         run: |
-          yarn add ts-node && make test-api-docs
+          yarn add ts-node
+      - name: Run api docs test
+        run: make test-api-docs
 
   backend-test:
     if: needs.files-changed.outputs.backend == 'true'
@@ -67,6 +76,8 @@ jobs:
     name: backend test
     runs-on: ubuntu-22.04
     timeout-minutes: 60
+    permissions:
+      actions: write
     strategy:
       # This helps not having to run multiple jobs because one fails, thus, reducing resource usage
       # and reducing the risk that one of many runs would turn red again (read: intermittent tests)
@@ -82,7 +93,8 @@ jobs:
       MATRIX_INSTANCE_TOTAL: 11
 
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
         with:
           # Avoid codecov error message related to SHA resolution:
           # https://github.com/codecov/codecov-bash/blob/7100762afbc822b91806a6574658129fe0d23a7d/codecov#L891
@@ -120,12 +132,15 @@ jobs:
     name: backend migration tests
     runs-on: ubuntu-22.04
     timeout-minutes: 30
+    permissions:
+      actions: write
     strategy:
       matrix:
         pg-version: ['14']
 
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
         with:
           # Avoid codecov error message related to SHA resolution:
           # https://github.com/codecov/codecov-bash/blob/7100762afbc822b91806a6574658129fe0d23a7d/codecov#L891
@@ -139,8 +154,8 @@ jobs:
           pg-version: ${{ matrix.pg-version }}
 
       - name: run tests
+        # historic migrations trigger some warnings
         run: |
-          # historic migrations trigger some warnings
           PYTEST_ADDOPTS="$PYTEST_ADDOPTS -m migrations --migrations" make test-python-ci
 
       # Upload coverage data even if running the tests step fails since
@@ -157,11 +172,14 @@ jobs:
     name: cli test
     runs-on: ubuntu-22.04
     timeout-minutes: 10
+    permissions:
+      actions: write
     strategy:
       matrix:
         pg-version: ['14']
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
 
       - name: Setup sentry env
         uses: ./.github/actions/setup-sentry
@@ -187,29 +205,36 @@ jobs:
     name: requirements check
     runs-on: ubuntu-22.04
     timeout-minutes: 3
+    permissions:
+      contents: write
     steps:
-      - uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
+      - name: Fetch GitHub auth token
+        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc  # v3.0.0
         id: token
         continue-on-error: true
         with:
           app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
           private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-      - uses: getsentry/action-setup-venv@f0daafa9688e48f939cace0378a46f2d422bd81f # v2.0.0
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
+      - name: Checkout repository
+        uses: getsentry/action-setup-venv@f0daafa9688e48f939cace0378a46f2d422bd81f  # v2.0.0
         with:
           python-version: 3.11.6
           cache-dependency-path: requirements-dev-frozen.txt
           install-cmd: python3 -m tools.hack_pip && pip install -q --constraint requirements-dev-frozen.txt pip-tools
-      - name: check requirements
-        run: |
-          python -S -m tools.freeze_requirements
-          if ! git diff --exit-code; then
-            echo $'\n\nrun `make freeze-requirements` locally to update requirements'
-            exit 1
-          fi
+      - name: Freeze requirements
+        run: python -S -m tools.freeze_requirements
+      - name: Check if this changes the files
+        id: git-check
+        run: echo "diff=$(git diff --exit-code)" >> $GITHUB_OUTPUT
+      - name: run make freeze-requirements locally to update requirements
+        if: steps.git-check.outputs.diff
+        run: exit 1
+
       - name: apply any requirements changes
         if: steps.token.outcome == 'success' && github.ref != 'refs/heads/master' && always()
-        uses: getsentry/action-github-commit@31f6706ca1a7b9ad6d22c1b07bf3a92eabb05632 # v2.0.0
+        uses: getsentry/action-github-commit@31f6706ca1a7b9ad6d22c1b07bf3a92eabb05632  # v2.0.0
         with:
           github-token: ${{ steps.token.outputs.token }}
           message: ':snowflake: re-freeze requirements'
@@ -219,13 +244,15 @@ jobs:
     needs: files-changed
     name: check migration
     runs-on: ubuntu-22.04
+    timeout-minutes: 2
     strategy:
       matrix:
         pg-version: ['14']
+    permissions: {}
 
     steps:
       - name: Checkout sentry
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
 
       - name: Setup sentry env
         uses: ./.github/actions/setup-sentry
@@ -246,8 +273,11 @@ jobs:
     name: monolith-dbs test
     runs-on: ubuntu-22.04
     timeout-minutes: 20
+    permissions:
+      actions: write
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
         with:
           # Avoid codecov error message related to SHA resolution:
           # https://github.com/codecov/codecov-bash/blob/7100762afbc822b91806a6574658129fe0d23a7d/codecov#L891
@@ -275,24 +305,31 @@ jobs:
     name: backend typing
     runs-on: ubuntu-22.04
     timeout-minutes: 20
+    permissions:
+      contents: write
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
 
-      - uses: getsentry/action-setup-venv@f0daafa9688e48f939cace0378a46f2d422bd81f # v2.0.0
+      - name: Setup venv
+        uses: getsentry/action-setup-venv@f0daafa9688e48f939cace0378a46f2d422bd81f  # v2.0.0
         with:
           python-version: 3.11.6
           cache-dependency-path: requirements-dev-frozen.txt
           install-cmd: python3 -m tools.hack_pip && pip install -r requirements-dev-frozen.txt
 
-      - name: setup sentry (lite)
-        run: |
-          python3 -m tools.fast_editable --path .
-          sentry init
+      - name: Run fast_editable
+        run: python3 -m tools.fast_editable --path .
 
-      - run: mypy
+      - name: init sentry
+        run: sentry init
+
+      - name: Run mypy
+        run: mypy
         id: run
 
-      - uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
+      - name: Fetch GitHub auth token
+        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc  # v3.0.0
         id: token
         continue-on-error: true
         with:
@@ -300,22 +337,15 @@ jobs:
           private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
 
       # only if `mypy` succeeds should we try and trim the blocklist
-      - run: python3 -m tools.mypy_helpers.make_module_ignores
+      - name: run mypy_helpers.make_module_ignores
+        run: python3 -m tools.mypy_helpers.make_module_ignores
         id: regen-blocklist
 
-      - run: git diff --exit-code
+      - name: Run git d0ff
+        run: git diff --exit-code
 
-      - run: |
-          # mypy does not have granular codes so don't allow specific messages to regress
-          ! grep "'Settings' object has no attribute" .artifacts/mypy-all
-          ! grep 'Cannot override class variable' .artifacts/mypy-all
-          ! grep 'Exception type must be derived from BaseException' .artifacts/mypy-all
-          ! grep 'Incompatible default for argument' .artifacts/mypy-all
-          ! grep 'Incompatible return value type (got "HttpResponseBase"' .artifacts/mypy-all
-          ! grep 'Incompatible types in "yield"' .artifacts/mypy-all
-          ! grep 'Module "sentry.*has no attribute' .artifacts/mypy-all
-          ! grep 'base class .* defined the type as.*Permission' .artifacts/mypy-all
-          ! grep 'does not explicitly export attribute' .artifacts/mypy-all
+      - name: Check if failure in the mypy output
+        run: .github/workflows/scripts/check-mypy-output.sh
 
       - name: apply blocklist changes
         if: |
@@ -324,7 +354,7 @@ jobs:
           steps.regen-blocklist.outcome == 'success' &&
           github.ref != 'refs/heads/master' &&
           always()
-        uses: getsentry/action-github-commit@31f6706ca1a7b9ad6d22c1b07bf3a92eabb05632 # v2.0.0
+        uses: getsentry/action-github-commit@31f6706ca1a7b9ad6d22c1b07bf3a92eabb05632  # v2.0.0
         with:
           github-token: ${{ steps.token.outputs.token }}
           message: ':knife: regenerate mypy module blocklist'
@@ -349,10 +379,14 @@ jobs:
     # This is necessary since a failed/skipped dependent job would cause this job to be skipped
     if: always()
     runs-on: ubuntu-22.04
+    timeout-minutes: 1
     steps:
       # If any jobs we depend on fail, we will fail since this is a required check
       # NOTE: A timeout is considered a failure
       - name: Check for failures
         if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
         run: |
-          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
+          echo "One of the dependent jobs have failed. You may need to re-run it."
+      - name: Fail pipeline if failed earlier
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: exit 1
diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -22,6 +22,7 @@ jobs:
     name: detect what files changed
     runs-on: ubuntu-22.04
     timeout-minutes: 3
+    permissions: {}
     # Map a step output to a job output
     outputs:
       lintable_css_in_js_modified: ${{ steps.changes.outputs.lintable_css_in_js_modified }}
@@ -35,10 +36,11 @@ jobs:
       testable_rules_changed: ${{ steps.changes.outputs.testable_rules_changed }}
       frontend_all: ${{ steps.changes.outputs.frontend_all }}
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
 
       - name: Check for frontend file changes
-        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
+        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd  # v3.0.0
         id: changes
         with:
           token: ${{ github.token }}
@@ -50,29 +52,35 @@ jobs:
     needs: files-changed
     name: typescript and lint
     runs-on: ubuntu-22.04
+    timeout-minutes: 3
+    permissions:
+      contents: write
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Checkout repository
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
 
       - name: Internal github app token
         id: token
-        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
+        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc  # v3.0.0
         continue-on-error: true
         with:
           app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
           private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
 
-      - uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581 # v2.0.0
+      - name: Setup volta
+        uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581  # v2.0.0
 
       - name: Install dependencies
         id: dependencies
         run: yarn install --frozen-lockfile
 
       # Setup custom tsc matcher, see https://github.com/actions/setup-node/issues/97
-      - name: setup matchers
-        run: |
-          echo "::remove-matcher owner=masters::"
-          echo "::add-matcher::.github/tsc.json"
-          echo "::add-matcher::.github/eslint-stylish.json"
+      - name: Add matchers masters
+        run: echo "::remove-matcher owner=masters::"
+      - name: Add matchers tsc
+        run: echo "::add-matcher::.github/tsc.json"
+      - name: Add matchers eslint-stylish
+        run: echo "::add-matcher::.github/eslint-stylish.json"
 
       # When we're on master we can run all tasks across all files
       # or if lint rules have changed, run the related task across all files
@@ -114,13 +122,20 @@ jobs:
       # forks do not have access to said token
       - name: Check for dirty git working tree (forks)
         if: github.ref != 'refs/heads/master' && steps.token.outcome != 'success'
+        id: git_check
         run: |
-          git diff --quiet || (echo '::error ::lint produced file changes, run linter locally and try again' && exit 1)
+          echo "result=git diff --quiet" >> $GITHUB_OUTPUT
+      - name:
+        if: github.ref != 'refs/heads/master' && steps.token.outcome != 'success' && steps.git_check.outputs.result
+        run: echo '::error ::lint produced file changes, run linter locally and try again'
+      - name: Fail pipeline if working tree is dirty
+        if: github.ref != 'refs/heads/master' && steps.token.outcome != 'success' && steps.git_check.outputs.result
+        run: exit 1
 
       # If working tree is dirty, commit and update if we have a token
       - name: Commit any eslint fixed files
         if: github.ref != 'refs/heads/master' && steps.token.outcome == 'success'
-        uses: getsentry/action-github-commit@31f6706ca1a7b9ad6d22c1b07bf3a92eabb05632 # v2.0.0
+        uses: getsentry/action-github-commit@31f6706ca1a7b9ad6d22c1b07bf3a92eabb05632  # v2.0.0
         with:
           github-token: ${{ steps.token.outputs.token }}
           message: ':hammer_and_wrench: apply eslint style fixes'
@@ -146,20 +161,21 @@ jobs:
         # XXX: When updating this, make sure you also update CI_NODE_TOTAL.
 
         instance: [0, 1, 2, 3]
-
+    permissions:
+      actions: write
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-        name: Checkout sentry
-
+      - name: Checkout sentry
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
         with:
           # Avoid codecov error message related to SHA resolution:
           # https://github.com/codecov/codecov-bash/blob/7100762afbc822b91806a6574658129fe0d23a7d/codecov#L891
           fetch-depth: '2'
 
-      - uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581 # v2.0.0
+      - name: Setup volta
+        uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581  # v2.0.0
 
       - name: node_modules cache
-        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
+        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2  # v4.0.0
         id: nodemodulescache
         with:
           path: node_modules
@@ -208,6 +224,7 @@ jobs:
     name: Frontend
     # This is necessary since a failed/skipped dependent job would cause this job to be skipped
     if: always()
+    timeout-minutes: 1
     runs-on: ubuntu-22.04
     steps:
       # If any jobs we depend on fail, we will fail since this is a required check
@@ -215,4 +232,7 @@ jobs:
       - name: Check for failures
         if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
         run: |
-          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
+          echo "One of the dependent jobs have failed. You may need to re-run it."
+      - name: Fail pipeline if failed previously
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: exit 1
